### ISSUE TITLE
Error for basic example: KeyError: 'QM_HOLIDAY'

### ISSUE THREAD

**Issue by ThoEngel** [thomasgermain/vr900-connector#33]
Environment:
Version of vr900-connector 0.3.1
Python 3.6.9

If i start the basic example from github:
```
from vr900connector.systemmanager import SystemManager
manager = SystemManager('myemail', 'mypassword')
system = manager.get_system()
```
I get the following error:
```
2019-07-29 20:27:43,908:INFO:Connector: No previous session found, will try to logging with username: myemail@email.de and smartphoneId: vr900-connector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/vr900connector/systemmanager.py", line 49, in get_system
    quickMode = Mapper.quick_mode(full_system)
  File "/usr/local/lib/python3.6/dist-packages/vr900connector/model/mapper.py", line 16, in quick_mode
    qm = QuickMode[quick_mode.get("quickmode")]
  File "/usr/lib/python3.6/enum.py", line 329, in __getitem__
    return cls._member_map_[name]
KeyError: 'QM_HOLIDAY'
```

What is going wrong?

**Comment by thomasgermain** [comment]
Hi,

what kind of device do you have ?

I guess your facility is in holiday mode ?

Could you show me the ouput of this: (please, remove persnnal data) 
```python
from vr900connector.api import ApiConnector, Urls
connector = ApiConnector('user', 'pass')
print(connector.get(Urls.system()))
```

**Comment by thomasgermain** [comment]
This should be fixed with version 0.3.2

**Comment by ThoEngel** [comment]
yes, my facility is in holiday mode.
My device is a vaillant  ecoTEC plus VC 146/5 E
Output of Version vr900-connector 0.3.1:
```
{'body': {'zones': [{'heating': {'configuration': {'mode': 'OFF', 'setback_temperature': 15.0, 'setpoint_temperature': 26.0}, 'timeprogram': {'monday': [{'startTime': '00:00', 'setting': 'NIGHT'}, {'startTime': '05:10', 'setting': 'DAY'}, {'startTime': '21:30', 'setting': 'NIGHT'}], 'tuesday': [{'startTime': '00:00', 'setting': 'NIGHT'}, {'startTime': '05:10', 'setting': 'DAY'}, {'startTime': '21:30', 'setting': 'NIGHT'}], 'wednesday': [{'startTime': '00:00', 'setting': 'NIGHT'}, {'startTime': '05:10', 'setting': 'DAY'}, {'startTime': '21:30', 'setting': 'NIGHT'}], 'thursday': [{'startTime': '00:00', 'setting': 'NIGHT'}, {'startTime': '05:10', 'setting': 'DAY'}, {'startTime': '21:30', 'setting': 'NIGHT'}], 'friday': [{'startTime': '00:00', 'setting': 'NIGHT'}, {'startTime': '05:10', 'setting': 'DAY'}, {'startTime': '21:30', 'setting': 'NIGHT'}], 'saturday': [{'startTime': '00:00', 'setting': 'NIGHT'}, {'startTime': '05:10', 'setting': 'DAY'}, {'startTime': '22:00', 'setting': 'NIGHT'}], 'sunday': [{'startTime': '00:00', 'setting': 'NIGHT'}, {'startTime': '05:10', 'setting': 'DAY'}, {'startTime': '21:30', 'setting': 'NIGHT'}]}}, 'configuration': {'name': 'ZONE 1', 'enabled': True, 'active_function': 'STANDBY', 'inside_temperature': 26.9, 'quickmode': {'quickmode': 'QM_HOLIDAY'}, 'quick_veto': {'active': False, 'setpoint_temperature': 24.0}}, 'currently_controlled_by': {'name': 'HOLIDAY_MODE', 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones'}}, '_id': 'Control_ZO1'}], 'configuration': {'quickmode': {'quickmode': 'QM_HOLIDAY', 'duration': 0}, 'eco_mode': True, 'holidaymode': {'active': True, 'start_date': '2019-07-27', 'end_date': '2019-08-03', 'temperature_setpoint': 16.0}}, 'status': {'datetime': '2019-07-29T20:33:05.000Z', 'outside_temperature': 23.4}, 'parameters': [{'name': 'Betriebsart Warmwasserkreis', 'definition': {'values': ['AUTO', 'DAY', 'OFF']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/dhw/Control_DHW/hotwater/configuration/operation_mode'}}, {'name': 'Betriebsart Heizen', 'definition': {'values': ['AUTO', 'SETBACK', 'OFF']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/heating/configuration/mode'}}, {'name': 'Betriebsart: Kühlen', 'definition': {'values': []}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/cooling/configuration/mode'}}, {'name': 'Nachttemperatur', 'definition': {'min': 5.0, 'max': 30.0, 'stepsize': 0.5}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/heating/configuration/setback_temperature'}}, {'name': 'Quick Veto Raumsolltemperatur', 'definition': {'min': 5.0, 'max': 30.0, 'stepsize': 0.5}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/configuration/quick_veto'}}, {'name': 'Raumsolltemperatur Tag', 'definition': {'min': 5.0, 'max': 30.0, 'stepsize': 0.5}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/heating/configuration/setpoint_temperature'}}, {'name': 'Sonderbetriebsart, die aktiviert wurde', 'definition': {'values': ['NO_QUICK_MODE', 'QM_PARTY', 'QM_VENTILATION_BOOST', 'QM_ONE_DAY_AT_HOME', 'QM_ONE_DAY_AWAY']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/configuration/quickmode'}}, {'name': 'Tagtemperatur Kühlen', 'definition': {'min': 15.0, 'max': 30.0, 'stepsize': 0.5}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/cooling/configuration/setpoint_temperature'}}, {'name': 'Betriebsart Lüften', 'definition': {'values': ['AUTO', 'NIGHT', 'DAY']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/ventilation/Control_SYS_MultiMatic/fan/configuration/operation_mode'}}, {'name': 'Maximale Lüftungsstufe Nacht', 'definition': {'min': 1.0, 'max': 6.0, 'stepsize': 1.0}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/ventilation/Control_SYS_MultiMatic/fan/configuration/night_level'}}, {'name': 'Maximale Lüftungsstufe Tag', 'definition': {'min': 1.0, 'max': 6.0, 'stepsize': 1.0}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/ventilation/Control_SYS_MultiMatic/fan/configuration/day_level'}}, {'name': 'Raumsolltemperatur für Tage außer Haus', 'definition': {'min': 5.0, 'max': 30.0, 'stepsize': 1.0}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/configuration/holidaymode'}}, {'name': 'Sonderbetriebsart, die aktiviert wurde', 'definition': {'values': ['NO_QUICK_MODE', 'QM_PARTY', 'QM_VENTILATION_BOOST', 'QM_ONE_DAY_AT_HOME', 'QM_ONE_DAY_AWAY']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/configuration/quickmode'}}, {'name': 'HEATING', 'definition': {'values': ['NIGHT', 'DAY']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/heating/timeprogram'}}, {'name': 'COOLING', 'definition': {'values': ['OFF', 'ON']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/cooling/timeprogram'}}, {'name': 'HOTWATER', 'definition': {'values': ['OFF', 'ON']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/dhw/Control_DHW/hotwater/timeprogram'}}, {'name': 'CIRCULATION_PUMP', 'definition': {'values': ['OFF', 'ON']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/dhw/Control_DHW/circulation/timeprogram'}}, {'name': 'VENTILATION', 'definition': {'values': ['NIGHT', 'DAY']}, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/ventilation/Control_SYS_MultiMatic/fan/timeprogram'}}], 'dhw': [{'hotwater': {'configuration': {'operation_mode': 'AUTO', 'temperature_setpoint': 62.0}, 'timeprogram': {'monday': [{'startTime': '00:00', 'mode': 'OFF'}, {'startTime': '05:30', 'mode': 'ON'}, {'startTime': '08:00', 'mode': 'OFF'}], 'tuesday': [{'startTime': '00:00', 'mode': 'OFF'}, {'startTime': '05:30', 'mode': 'ON'}, {'startTime': '08:00', 'mode': 'OFF'}], 'wednesday': [{'startTime': '00:00', 'mode': 'OFF'}, {'startTime': '05:30', 'mode': 'ON'}, {'startTime': '08:00', 'mode': 'OFF'}], 'thursday': [{'startTime': '00:00', 'mode': 'OFF'}, {'startTime': '05:30', 'mode': 'ON'}, {'startTime': '08:00', 'mode': 'OFF'}], 'friday': [{'startTime': '00:00', 'mode': 'OFF'}, {'startTime': '05:30', 'mode': 'ON'}, {'startTime': '08:00', 'mode': 'OFF'}], 'saturday': [{'startTime': '00:00', 'mode': 'OFF'}, {'startTime': '05:30', 'mode': 'ON'}, {'startTime': '08:00', 'mode': 'OFF'}], 'sunday': [{'startTime': '00:00', 'mode': 'OFF'}, {'startTime': '05:30', 'mode': 'ON'}, {'startTime': '08:00', 'mode': 'OFF'}]}}, 'circulation': {'configuration': {'operationMode': 'AUTO'}, 'timeprogram': {'monday': [{'startTime': '00:00', 'setting': 'OFF'}, {'startTime': '06:00', 'setting': 'ON'}, {'startTime': '22:00', 'setting': 'OFF'}], 'tuesday': [{'startTime': '00:00', 'setting': 'OFF'}, {'startTime': '06:00', 'setting': 'ON'}, {'startTime': '22:00', 'setting': 'OFF'}], 'wednesday': [{'startTime': '00:00', 'setting': 'OFF'}, {'startTime': '06:00', 'setting': 'ON'}, {'startTime': '22:00', 'setting': 'OFF'}], 'thursday': [{'startTime': '00:00', 'setting': 'OFF'}, {'startTime': '06:00', 'setting': 'ON'}, {'startTime': '22:00', 'setting': 'OFF'}], 'friday': [{'startTime': '00:00', 'setting': 'OFF'}, {'startTime': '06:00', 'setting': 'ON'}, {'startTime': '22:00', 'setting': 'OFF'}], 'saturday': [{'startTime': '00:00', 'setting': 'OFF'}, {'startTime': '06:00', 'setting': 'ON'}, {'startTime': '22:00', 'setting': 'OFF'}], 'sunday': [{'startTime': '00:00', 'setting': 'OFF'}, {'startTime': '06:00', 'setting': 'ON'}, {'startTime': '22:00', 'setting': 'OFF'}]}}, '_id': 'Control_DHW'}]}, 'meta': {'resourceState': [{'state': 'OUTDATED', 'timestamp': 1564478206818, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/status'}}, {'state': 'OUTDATED', 'timestamp': 1564478206818, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/configuration'}}, {'state': 'OUTDATED', 'timestamp': 1564478206818, 'link': {'rel': 'child', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/configuration/holidaymode'}}, {'state': 'OUTDATED', 'timestamp': 1564478206818, 'link': {'rel': 'child', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/configuration/quickmode'}}, {'state': 'OUTDATED', 'timestamp': 1564478206817, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/heating/configuration'}}, {'state': 'OUTDATED', 'timestamp': 1564435211000, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/heating/timeprogram'}}, {'state': 'OUTDATED', 'timestamp': 1564478206817, 'link': {'rel': 'child', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/configuration/quick_veto'}}, {'state': 'OUTDATED', 'timestamp': 1564478206817, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/zones/Control_ZO1/configuration'}}, {'state': 'SYNCED', 'timestamp': 1564478206830, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/dhw/Control_DHW/circulation/configuration'}}, {'state': 'SYNCED', 'timestamp': 1564478206830, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/dhw/Control_DHW/hotwater/configuration'}}, {'state': 'OUTDATED', 'timestamp': 1564435211000, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/dhw/Control_DHW/circulation/timeprogram'}}, {'state': 'OUTDATED', 'timestamp': 1564435211000, 'link': {'rel': 'self', 'resourceLink': '/facilities/21172200201971160933012007N7/systemcontrol/v1/dhw/Control_DHW/hotwater/timeprogram'}}]}}
```
In the next step i will update to verison 0.3.2.

**Comment by ThoEngel** [comment]
Version of vr900-connector 0.3.2
Python 3.6.9
The basic example (vr900-connector 0.3.2) from github works without errors.
