### ISSUE TITLE
Installation error on raspberry pi 3

### ISSUE THREAD

**Issue by ThoEngel** [thomasgermain/vr900-connector#4]
After installation on a raspberry pi 3 i get the following error:
```
pi@raspberrypi:~/vr900-connector $ python3 setup.py pytest
running pytest
Searching for pytest
Best match: pytest 4.3.0
Processing pytest-4.3.0-py3.5.egg

Using /home/pi/vr900-connector/.eggs/pytest-4.3.0-py3.5.egg
Searching for responses
Best match: responses 0.10.5
Processing responses-0.10.5-py3.5.egg

Using /home/pi/vr900-connector/.eggs/responses-0.10.5-py3.5.egg
Searching for py>=1.5.0
Best match: py 1.8.0
Processing py-1.8.0-py3.5.egg

Using /home/pi/vr900-connector/.eggs/py-1.8.0-py3.5.egg
Searching for pluggy>=0.7
Best match: pluggy 0.8.1
Processing pluggy-0.8.1-py3.5.egg

Using /home/pi/vr900-connector/.eggs/pluggy-0.8.1-py3.5.egg
Searching for pathlib2>=2.2.0; python_version < "3.6"
Best match: pathlib2 2.3.3
Processing pathlib2-2.3.3-py3.5.egg

Using /home/pi/vr900-connector/.eggs/pathlib2-2.3.3-py3.5.egg
Searching for more-itertools>=4.0.0; python_version > "2.7"
Best match: more-itertools 6.0.0
Processing more_itertools-6.0.0-py3.5.egg

Using /home/pi/vr900-connector/.eggs/more_itertools-6.0.0-py3.5.egg
Searching for atomicwrites>=1.0
Best match: atomicwrites 1.3.0
Processing atomicwrites-1.3.0-py3.5.egg

Using /home/pi/vr900-connector/.eggs/atomicwrites-1.3.0-py3.5.egg
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    install_requires=["requests", "responses", "pytest"])
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/pi/vr900-connector/.eggs/pytest_runner-4.4-py3.5.egg/ptr.py", line 183, in run
  File "/home/pi/vr900-connector/.eggs/pytest_runner-4.4-py3.5.egg/ptr.py", line 131, in install_dists
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 194, in install_dists
    ir_d = dist.fetch_build_eggs(dist.install_requires or [])
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1111, in best_match
    dist = working_set.find(req)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 715, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (chardet 2.3.0 (/usr/lib/python3/dist-packages), Requirement.parse('chardet<3.1.0,>=3.0.2'))
```

What is going wrong?

**Comment by thomasgermain** [comment]
Hmm never tried yet on a raspberry.

Could you try updating chardet ? It seems you have version 2.3.0 and something requires at least version 3.0.2
